steps:
  # build tools in parallel
  - name: "gcr.io/kaniko-project/executor:latest"
    waitFor: ["-"]
    dir: "imagemagick"
    args:
      - --destination=gcr.io/$PROJECT_ID/imagemagick:latest
      - --cache=true
      - --cache-ttl=96h
