steps:
  # - name: "gcr.io/kaniko-project/executor:latest"
  #   dir: "archlinux"
  #   args:
  #     - --cache
  #     - --context=/workspace/archlinux
  #     - --destination=gcr.io/$PROJECT_ID/archlinux:latest
  - name: "gcr.io/cloud-builders/docker:latest"
    dir: "archlinux"
    args:
      - build
      - -t
      - "gcr.io/$PROJECT_ID/archlinux"
      - .
