steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    dir: "$_IMG"
    args:
      - "--cache"
      - "--context=/workspace/$_IMG"
      - "--destination=gcr.io/$PROJECT_ID/$_IMG:latest"
substitutions:
  _IMG: "makepkg"
